apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-app-isolation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hatan4ik/aks-troublshoot-guides
    targetRevision: main
    path: k8s/multi-app-isolation
  destination:
    server: https://kubernetes.default.svc
    namespace: app-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
